<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../VpsDesk.Domain/VpsDesk.Domain.csproj" />
    <ProjectReference Include="../VpsDesk.Application/VpsDesk.Application.csproj" />
    <PackageReference Include="SSH.NET" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>
</Project>
